name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: mstksg/get-package@v1
      with:
        apt-get: mono-mcs mtools syslinux syslinux-common jq curl
    - name: Install zig/master
      run: bash ./aux/install-zig.sh
    - name: Build boot.img
      run: PATH=$PATH:`pwd`/zig-current make -C kernel boot.img SYSLINUX_ROOT=/usr/lib/syslinux/modules
    - name: Build floppy.img
      run: PATH=$PATH:`pwd`/zig-current make -C kernel floppy.img SYSLINUX_ROOT=/usr/lib/syslinux/modules
