name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: mstksg/get-package@v1
      with:
        apt-get: mono-mcs mtools syslinux-common
    - name: Build boot.img
      run: make -C kernel boot.img
    - name: Build floppy.img
      run: make -C kernel floppy.img
